spring:
  datasource:
    url: jdbc:h2:mem:maindb
  sql:
    init:
      mode: always
      data-locations: data.sql
      schema-locations: schema.sql
  shell:
    interactive:
      enabled: true
  jpa:
    show-sql: true
    generate-ddl: false
    hibernate:
      ddl-auto: none